### ISSUE TITLE
Review on Morpho strategy

### ISSUE THREAD

**Issue by MerlinEgalite** [Idle-Labs/idle-tranches#67]
Did not find any flaws. I have a few remarks/comments:

**1. Initialization**

Below I would have used the [initializer](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/3c646a808ea4f73887bd0be5b78869332e067236/contracts/proxy/utils/Initializable.sol#L145-L151) helper form OZ and removed this [line](https://github.com/Idle-Labs/idle-tranches/blob/d78bc061e285d3304e8d1cce4ce89713347f2111/contracts/strategies/ERC4626Strategy.sol#L55). This makes easier to make sure that the implementation contract is already initialized too.
https://github.com/Idle-Labs/idle-tranches/blob/d78bc061e285d3304e8d1cce4ce89713347f2111/contracts/strategies/ERC4626Strategy.sol#L39-L42

**2. APR**

Why is it divided by `1e7` here?
https://github.com/Idle-Labs/idle-tranches/blob/d78bc061e285d3304e8d1cce4ce89713347f2111/contracts/strategies/morpho/MorphoAaveV2SupplyVaultStrategy.sol#L12

**3. ERC4626**

Should `ERC4626Strategy` implements the ERC4626 interface?

**4. Misleading comments**

https://github.com/Idle-Labs/idle-tranches/blob/d78bc061e285d3304e8d1cce4ce89713347f2111/contracts/strategies/morpho/MorphoSupplyVaultStrategy.sol#L12-L16

**5. Check at initialization**

There is not check that the `strategyToken` corresponds to the correct `poolToken` and to the correct underlying `token`. That's to keep in mind at initialization.

**6. Token duplication in storage** 

https://github.com/Idle-Labs/idle-tranches/blob/d78bc061e285d3304e8d1cce4ce89713347f2111/contracts/strategies/ERC4626Strategy.sol#L22
https://github.com/Idle-Labs/idle-tranches/blob/d78bc061e285d3304e8d1cce4ce89713347f2111/contracts/strategies/ERC4626Strategy.sol#L34

**7. Useless variable?** 

`oneToken` is unused in the contract. Is it used offchain?

---
Other devs will check the code!

**Comment by bugduino** [comment]
Thanks for the review.
Below my comments:
1) yeah I think it would make more sense, it's an old workaround
2) because we want to have APR expressed as eg `1e18` for a 1% apr
3) I think that the strategy name is a bit misleading here, but we are not creating an ERC4626 strategy on our side in this specific file, but we are only integrating ERC4626 compliant vaults so it should not be needed
4-6-7) You are right those should be fixed
5) for this we usually don't do these kind of checks in the initialization (although it would be a good practice) as those will be made directly on chain with our test deposits

**Comment by pakim249CAL** [comment]
I have nothing substantial to add beyond what's been said.

For 3, I agree with you. This is a strategy making use of 4626. It is not a 4626 implementation itself.

I generally agree with points 6 & 7 but I think this is out of scope of what we should be reviewing.

**Comment by Rubilmax** [comment]
https://github.com/Idle-Labs/idle-tranches/blob/d78bc061e285d3304e8d1cce4ce89713347f2111/contracts/strategies/morpho/MorphoSupplyVaultStrategy.sol#L47

`claimRewards` does not exist on Morpho-AaveV2's ERC4626 vaults, so this call would revert on `MorphoAaveV2SupplyVaultStrategy`. Is this intended?

___

https://github.com/Idle-Labs/idle-tranches/blob/d78bc061e285d3304e8d1cce4ce89713347f2111/contracts/strategies/morpho/MorphoCompoundSupplyVaultStrategy.sol#L14

APR here is multiplied by 100, I suppose to get an APR in percentage and not as a fixed-point, 18 decimal, number. Why isn't the rate return from Morpho-AaveV2's Lens multiplied by 100 too?

___

**Comment by bugduino** [comment]
@Rubilmax that's interesting, we didn't tested that part (`_rewardToken` is set to addr0) given that we cannot harvest MORPHO tokens yet. Is there a specific method for claiming rewards different than the one for Mopho-Compound?

For the APR in general we try to always have in the 18 decimals format with 1e18 expressing 1%, in the case of aave the apr we get from the lens have 27 decimals, so we do `/ 1e9` to have it in 18 decimals format and then `*100` to have it in the format described above so we combine this in a single `/ 1e7`

**Comment by Rubilmax** [comment]
1. There are no more rewards distributed on AaveV2, that's the reason why there's no claim rewards method on morpho-aave-v2 vaults

2. Sorry, I read too fast your answer above and didn't realize that 1e7 was actually 1e9 / 100

**Comment by bugduino** [comment]
@MerlinEgalite I updated the comments but kept `oneToken` as it was needed by `IIdleCDOStrategy` interface and also `underlyingToken` because the Morpho instances are already deployed as upgradeable so I would mess up the storage in case any other future update is needed.

Thanks for the review @MerlinEgalite @Rubilmax @pakim249CAL I'm closing the issue now, if you have any further addition feel free to reopen it

**Comment by bugduino** [comment]
@Rubilmax just saw that MORPHO rewards for Aave markets have restarted
![Screenshot from 2023-02-07 18-18-40](https://user-images.githubusercontent.com/1852109/217317299-20cecc90-5b3f-45ae-816f-3183d5236a6f.png) was wondering if the `claimRewards` now will be added for maTokens too

**Comment by MerlinEgalite** [comment]
> @Rubilmax just saw that MORPHO rewards for Aave markets have restarted ! was wondering if the `claimRewards` now will be added for maTokens too

For maTokens users can claim $MORPHO rewards on this [rewards distributor contract](https://etherscan.io/address/0x60345417a227ad7e312eaa1b5ec5cd1fe5e2cdc6#code). There is no `claimRewards` for that in the code and there won't be. The `claimRewards` function on mcTokens are related to $COMP rewards and not $MORPHO rewards.
